-- HUMAN RESOURCE MACHINE PROGRAM --

    JUMP     b
a:
    COPYFROM [14]
    OUTBOX  
    BUMPUP   14
b:
c:
    COPYFROM 14
    COPYTO   13
    INBOX   
    COPYTO   [13]
d:
    BUMPDN   13
    JUMPN    a
    COPYFROM [14]
    SUB      [13]
    JUMPZ    c
    JUMP     d


DEFINE LABEL 13
eJzjYmBgYErkPsaUGDRXPulC7ouUr847yk7PkKzxXHektmLHkdrc8vP1+70YRsEoGAXDEgAAIT0R3Q;

DEFINE LABEL 14
eJwTZGBgcO0MUXjXekvlQLG3YWZBktmCXF+77sxr/stS2dLrknSa/JO2TD6d/GvRp7SmLZ5Zjvv78vJP
+pVYXvhYwXs5tyfgKsMoGAWjYMgCABnBHwU;

